name: learn_space
description: The Learning App As schools around the world respond to the “new normal”, the need for remote learning tools has never been more urgent. This  can help schools, educators, students, and their families to make the transition to distance learning easier.  

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_pro: ^1.0.0
  flutter_swiper: ^1.1.6
  simple_animations: ^2.2.2
  curved_navigation_bar: ^0.3.4
  cloud_firestore:
  firebase_auth:
  firebase_core:
  firebase_user_stream:
  google_sign_in:
  firebase_messaging:
  shimmer: ^1.1.2
  firebase_database:
  auto_size_text: ^2.1.0
  google_fonts: ^1.1.1
  email_validator: ^1.0.6
  shared_preferences: ^0.5.12+2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"
  flutter_launcher_name: "^0.0.1"
flutter_icons:
  android: true
  ios: true
  image_path: "Images/appstore.png"

flutter_launcher_name:
  name: "LearnSpace"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - Images/p1.jpeg
    - Images/p2.jpeg
    - Images/p3.jpeg
    - Images/p4.jpeg
    - Images/p5.jpeg
    - Images/p6.jpeg
    - Images/p7.jpeg
    - Images/p8.jpeg
    - Images/b1.jpg
    - Images/b2.jpg
    - Images/b3.jpg
    - Images/b4.jpg
    - Images/L1.png
    - Images/L2.png
    - Images/L3.png
    - Images/L4.png
    - Images/bg.png
    - Images/search.png
    - Images/sendmessage.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/Fonts/Pacifico-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
